/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    pages: Page;
    media: Media;
    badges: Badge;
    interviews: Interview;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface User {
  id: string;
  firstName?: string | null;
  lastName?: string | null;
  userName: string;
  roles?: ('admin' | 'editor' | 'endUser')[] | null;
  userBadges?:
    | {
        badge: string | Badge;
        bio: string;
        services: {
          name: string;
          url: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  seo: Seo;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface Badge {
  id: string;
  singularName: string;
  pluralName: string;
  seo: Seo;
  updatedAt: string;
  createdAt: string;
}
export interface Seo {
  slug: string;
  title?: string | null;
  description?: string | null;
  excerpt?: string | null;
  image?: string | Media | null;
  keywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
}
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Page {
  id: string;
  name: string;
  richText?: {
    root: {
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      type: string;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  richText_html?: string | null;
  seo: Seo;
  updatedAt: string;
  createdAt: string;
}
export interface Interview {
  id: string;
  name: string;
  badge: string | Badge;
  questions: {
    question: {
      index: number;
      shortQuestion: string;
      mediumQuestion: string;
      longQuestion: string;
      seo: Seo;
      answers?:
        | {
            user: string | User;
            answer?: {
              richText?: {
                root: {
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  type: string;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              richText_html?: string | null;
              images?:
                | {
                    image?: string | Media | null;
                    id?: string | null;
                  }[]
                | null;
              video?: string | Media | null;
            };
            id?: string | null;
          }[]
        | null;
    };
    id?: string | null;
  }[];
  seo: Seo;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}